version: "3.9"

services:
  # 1. DATABASE
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: openmuc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data

  # 2. OPENMUC
  openmuc:
    build:
      context: .
      dockerfile: Dockerfile.openmuc
    image: openmuc:latest
    container_name: openmuc
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8888:8888"
    privileged: true
    volumes:
      - /dev/:/dev
      - ./framework:/app/framework

  # 3. BACKEND (Spring Boot)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: bms-backend:latest
    container_name: bms-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - openmuc
    ports:
      - "8081:8081"
    environment:
      TZ: Asia/Bangkok
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/openmuc
      SPRING_DATASOURCE_USERNAME: openmuc_user
      SPRING_DATASOURCE_PASSWORD: openmuc
      # Backend gọi OpenMUC qua tên service 'openmuc'
      OPENMUC_URL: http://openmuc:8888

  # 4. FRONTEND (Angular + Node Proxy)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: bms-frontend:latest
    container_name: bms-frontend
    restart: unless-stopped
    depends_on:
      - backend
      - openmuc
    ports:
      # Map cổng 8080 máy chủ vào cổng 80 container (nơi server.js chạy)
      - "8080:80"
    environment:
      TZ: Asia/Bangkok
      # Frontend gọi Backend qua tên container 'bms-backend'
      API_TARGET_8081: "http://bms-backend:8081"
      # Frontend gọi OpenMUC qua tên container 'openmuc'
      API_TARGET_8888: "http://openmuc:8888"
